# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: snapcraft
email: anthony.dillon@canonical.com
description: Introducing snaps and commands to install and remove them on Ubuntu 16.04 LTS.
baseurl: ""
navigation:
- text: Home
  url: /
- text: Get started
  url: /get-started/
exclude: ['LICENCE', 'README.md', 'Gulpfile.js', 'package.json', 'node_modules']

# Build settings
markdown: kramdown

# only build incrementally
incremental: true
